### ISSUE TITLE
Cannot achieve the accuracy mentioned in the paper

### ISSUE THREAD

**Issue by Saquibirtiza** [CGCL-codes/VulCNN#12]
After some tweaking in the code, I am finally able to run the method on my system using the default sent2vec model shared by the authors. But my accuracy is close to 53% which is way off from the 78% accuracy mentioned in the paper. Anyone facing the same issue or know how to improve the results? Screenshot shared for reference:

![image](https://github.com/CGCL-codes/VulCNN/assets/30957097/0fa6aab1-1029-48e4-8520-a2e4a4e1433d)

Note: I checked that the hyperparameters in the code are already set to the best ones according to the paper so I do not think that is the issue.

**Comment by Saquibirtiza** [comment]
What version of joern are you using?

**Comment by Byw111** [comment]
> 在对代码进行一些调整后，我终于能够使用作者共享的默认 sent2vec 模型在我的系统上运行该方法。但我的准确率接近 53%，这与论文中提到的 78% 准确率相去甚远。有人面临同样的问题或知道如何改进结果吗？截图分享供参考：
> 
> ![image](https://private-user-images.githubusercontent.com/30957097/250958614-0fa6aab1-1029-48e4-8520-a2e4a4e1433d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5Mjk1NjgsIm5iZiI6MTcyOTkyOTI2OCwicGF0aCI6Ii8zMDk1NzA5Ny8yNTA5NTg2MTQtMGZhNmFhYjEtMTAyOS00OGU0LTg1MjAtYTJlNGE0ZTE0MzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA3NTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZDQ3MjI1ZDBmOTQ3NWY1ZDQwYjExNDM5MDE4MGQxOWE2NTYzN2U0ZjAxZWFiZDE3NzJiZDIyMTJmNzRkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJczxYxQ7DoKYdWtWqInhCbXOEajVLwzha_nGe2foFI)

Did you get this result with a code change? I can't get the right results

**Comment by huangyuyan3** [comment]
> > 在对代码进行一些调整后，我终于能够使用作者共享的默认 sent2vec 模型在我的系统上运行该方法。但我的准确率接近 53%，这与论文中提到的 78% 准确率相去甚远。有人面临同样的问题或知道如何改进结果吗？截图分享供参考：
> > ![image](https://private-user-images.githubusercontent.com/30957097/250958614-0fa6aab1-1029-48e4-8520-a2e4a4e1433d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5Mjk1NjgsIm5iZiI6MTcyOTkyOTI2OCwicGF0aCI6Ii8zMDk1NzA5Ny8yNTA5NTg2MTQtMGZhNmFhYjEtMTAyOS00OGU0LTg1MjAtYTJlNGE0ZTE0MzNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA3NTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZDQ3MjI1ZDBmOTQ3NWY1ZDQwYjExNDM5MDE4MGQxOWE2NTYzN2U0ZjAxZWFiZDE3NzJiZDIyMTJmNzRkNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJczxYxQ7DoKYdWtWqInhCbXOEajVLwzha_nGe2foFI)
> 
> Did you get this result with a code change? I can't get the right results

May I ask if you have resolved this issue?
